---

- name: "configuration: Configure /usr/local/etc/php.ini"
  lineinfile:
    dest: "/usr/local/etc/php.ini"
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }} = \"{{ item.val }}\""
    insertafter: "{{ item.after | default(omit) }}"
    backup: yes
  loop: "{{ bsd_php_ini_conf }}"
  notify: reload apache

# EOF
...
