---
- name: "Conf: Create /usr/local/etc/php.ini"
  ansible.builtin.command:
    cmd: cp /usr/local/etc/php.ini-production /usr/local/etc/php.ini
    creates: /usr/local/etc/php.ini
  tags: fm_roundcube_conf_php_ini_create

- name: "Conf: Configure {{ bsd_php_ini_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ bsd_php_ini_file }}"
    regexp: ^{{ item.regex }}
    line: '{{ item.regex }} = "{{ item.val }}"'
    insertafter: "{{ item.after | d(omit) }}"
    backup: "{{ fm_roundcube_backup_conf }}"
  loop: "{{ bsd_php_ini_conf }}"
  notify: "{{ fm_reload_webserver }}"
  tags: fm_roundcube_conf_php_ini

- name: "Conf: Configure {{ roundcube_data_dir ~ '/config/config.inc.php' }}"
  ansible.builtin.template:
    src: config-config.inc.php.j2
    dest: "{{ roundcube_data_dir }}/config/config.inc.php"
    owner: "{{ roundcube_data_owner }}"
    group: "{{ roundcube_data_group }}"
    mode: "{{ roundcube_data_mode }}"
    backup: "{{ apache_backup_conf }}"
  notify: "{{ fm_reload_webserver }}"
  tags: fm_roundcube_conf_config_inc_php

# EOF
