---

- name: "copy: Create /usr/local/etc/php.ini"
  ansible.builtin.copy:
    src: /usr/local/etc/php.ini-production
    dest: /usr/local/etc/php.ini
    force: false
    remote_src: true

# EOF
...
