---
# tasks for freebsd_mailserver_roundcube

- name: Import webserver.yml
  ansible.builtin.import_tasks: webserver.yml
  tags: [fm_roundcube_webserver, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: fm_roundcube_debug|bool
  tags: fm_roundcube_debug

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: fm_roundcube_install|bool
  tags: fm_roundcube_packages

- name: Import permissions.yml
  ansible.builtin.import_tasks: permissions.yml
  tags: fm_roundcube_permissions

- name: Import copy.yml
  ansible.builtin.import_tasks: copy.yml
  tags: fm_roundcube_copy

- name: Import conf.yml
  ansible.builtin.import_tasks: conf.yml
  tags: fm_roundcube_conf

- name: Import plugins.yml
  ansible.builtin.import_tasks: plugins.yml
  tags: fm_roundcube_plugins

- name: Import initial_sql.yml
  ansible.builtin.import_tasks: initial_sql.yml
  when: fm_roundcube_initial_sql|bool
  tags: fm_roundcube_initial_sql

# EOF
...
