---
# tasks for freebsd-mailserver-roundcube

- import_tasks: webserver.yml
  tags: [fm_roundcube_webserver, always]

- import_tasks: debug.yml
  when: fm_roundcube_debug|bool
  tags: [fm_roundcube_debug, always]

- import_tasks: packages.yml
  when: fm_roundcube_install|bool
  tags: fm_roundcube_packages

- import_tasks: permissions.yml
  tags: fm_roundcube_permissions

- import_tasks: copy.yml
  tags: fm_roundcube_copy

- import_tasks: conf.yml
  tags: fm_roundcube_conf

- import_tasks: plugins.yml
  tags: fm_roundcube_plugins

- import_tasks: mysql_initial_sql.yml
  tags: fm_roundcube_initial_sql

# EOF
...
