---
# tasks for freebsd-mailserver-roundcube

- include: packages.yml
  tags:
    - packages
    - freebsd-mailserver-roundcube-packages
    - freebsd-mailserver-roundcube

- include: copy.yml
  tags:
    - roundcube-copy
    - freebsd-mailserver-roundcube-copy
    - freebsd-mailserver-roundcube

- include: templates.yml
  tags:
    - roundcube-templates
    - freebsd-mailserver-roundcube-templates
    - freebsd-mailserver-roundcube

- include: permissions.yml
  tags:
    - roundcube-permissions
    - freebsd-mailserver-roundcube-permissions
    - freebsd-mailserver-roundcube

- include: mysql.yml
  tags:
    - roundcube-mysql
    - freebsd-mailserver-roundcube-mysql
    - freebsd-mailserver-roundcube

- include: configuration.yml
  tags:
    - roundcube-configuration
    - freebsd-mailserver-roundcube-configuration
    - freebsd-mailserver-roundcube
