---
# tasks for freebsd-mailserver-roundcube

- import_tasks: packages.yml
  tags: fm_roundcube_packages

- import_tasks: permissions.yml
  tags: fm_roundcube_permissions

- import_tasks: copy.yml
  tags: fm_roundcube_copy

- import_tasks: configuration.yml
  tags: fm_roundcube_configuration

- import_tasks: templates.yml
  tags: fm_roundcube_templates

- import_tasks: mysql_initial_sql.yml
  tags: fm_roundcube_initial_sql

# EOF
...
