---
# tasks for freebsd-mailserver-roundcube

- include: packages.yml
  tags:
    - packages
    - freebsd-mailserver-roundcube_packages
    - freebsd-mailserver-roundcube

- include: copy.yml
  tags:
    - roundcube-configuration-copy
    - freebsd-mailserver-roundcube_roundcube-configuration-copy
    - freebsd-mailserver-roundcube

- include: templates.yml
  tags:
    - roundcube-configuration-templates
    - freebsd-mailserver-roundcube_roundcube-configuration-templates
    - freebsd-mailserver-roundcube

- include: permissions.yml
  tags:
    - roundcube-permissions-set
    - freebsd-mailserver-roundcube_roundcube-permissions-set
    - freebsd-mailserver-roundcube

- include: configuration.yml
  tags:
    - roundcube-configuration
    - freebsd-mailserver-roundcube_roundcube-configuration
    - freebsd-mailserver-roundcube
