---
- name: Install packages
  when: freebsd_install_method | lower == "packages"
  block:

    - name: "Packages: Install aspell packages"
      community.general.pkgng:
        name: "{{ roundcube_aspell_packages }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"

    - name: "Packages: Install roundcube packages"
      community.general.pkgng:
        name: "{{ roundcube_packages }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"

- name: Install ports
  when: freebsd_install_method | lower == "ports"
  block:

    - name: "Packages: Install aspell ports"
      community.general.portinstall:
        name: "{{ item }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ roundcube_aspell_packages }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"

    - name: "Packages: Install roundcube ports"
      community.general.portinstall:
        name: "{{ item }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ roundcube_packages }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"

# EOF
