---

- name: Install aspell packages
  pkgng: >
    name='{{item}}'
    state='present'
  with_items: "{{roundcube_aspell_packages}}"
  when: freebsd_install_method == "packages"
  tags: packages

- name: Install packages
  pkgng: >
    name='{{item}}'
    state='present'
  with_items: "{{roundcube_packages}}"
  when: freebsd_install_method == "packages"
  tags: packages

- name: Install aspell packages (from ports)
  portinstall: >
    name='{{item}}'
    state='present'
    use_packages="{{freebsd_use_packages}}"
  with_items: "{{roundcube_aspell_packages}}"
  when: freebsd_install_method == "ports"
  tags: ports

- name: Install packages (from ports)
  portinstall: >
    name='{{item}}'
    state='present'
    use_packages="{{freebsd_use_packages}}"
  with_items: "{{roundcube_packages}}"
  when: freebsd_install_method == "ports"
  tags: ports

# TODO
# Configure ports with ZTS
# +[x] ZTS       Force Zend Thread Safety (ZTS) build
# grep ZTS /var/db/ports/lang_php56*/options
# OPTIONS_FILE_SET+=ZTS
# grep ZTS /var/db/ports/www_mod_php56/options
# OPTIONS_FILE_SET+=ZTS
