---

- name: Set permissions of /usr/local/www/roundcube/
  file: >
    path="/usr/local/www/roundcube/"
    state="directory"
    owner="root"
    group="www"
    mode="u+rwX,g+rX,o-rwx"
    recurse="yes"

- name: Set group writable /usr/local/www/roundcube/temp
  file: >
    path="/usr/local/www/roundcube/temp"
    state="directory"
    owner="root"
    group="www"
    mode="g+w"
    recurse="yes"

- name: Set group writable /usr/local/www/roundcube/logs
  file: >
    path="/usr/local/www/roundcube/logs"
    state="directory"
    owner="root"
    group="www"
    mode="g+w"
    recurse="yes"
