---

- name: "permissions: chown -R {{ roundcube_data_owner }}:{{ roundcube_data_group }} /usr/local/www/roundcube"
  command: "chown -R {{ roundcube_data_owner }}:{{ roundcube_data_group }} roundcube"
  args:
    chdir: /usr/local/www
    warn: false
  changed_when: false

- name: "permissions: chmod -R {{ roundcube_data_mode }} /usr/local/www/roundcube"
  command: "chmod -R {{ roundcube_data_mode }} /usr/local/www/roundcube"
  args:
    chdir: /usr/local/www
    warn: false
  changed_when: false

# EOF
...
