---
- name: Apache
  when: fm_roundcube_apache | bool
  tags: always
  block:

    - name: "Webserver: Apache: Include role"
      ansible.builtin.include_role:
        name: vbotka.apache
        tasks_from: vars.yml
        public: true
        apply:
          tags: always

    - name: "Webserver: Apache: Set handlers names"
      ansible.builtin.set_fact:
        fm_reload_webserver: reload apache

# EOF
