---
# handlers for freebsd-mailserver-roundcube

- name: enable and start apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: disable and stop apache
  service:
    name: "{{ apache_service }}"
    state: stopped
    enabled: false

- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: reload apache
  service:
    name: "{{ apache_service }}"
    state: reloaded

# EOF
...
